### ISSUE TITLE
Use of term "GNU"

### ISSUE THREAD

**Issue by denilsonsa** [ArduinoHistory/arduinohistory.github.io#3]
> there wasn’t a GNU (i.e. open source) toolchain available

I'm not sure if I understood what you meant.

There is a GNU toolchain, it is composed by `gcc`, `automake`, and similar tools. We can say that because those tools are part of the _GNU project_, i.e. they are developed by the FSF (Free Software Foundation).

However, tools like Xorg, TeX, `vim` and `avrdude` are free software, but are not GNU; because they are not from GNU/FSF.

https://www.gnu.org/software/software.html

In your text, it seems you are using GNU as a synonym for _free software_ or _open source software_. If that is the case, it is incorrect. I believe that is what you meant; but that is not what is written.

Footnote: There is still a difference between _free software_ and _open source software_, but I won't comment on it.

**Comment by bhagman** [comment]
Yes - that was an odd thing to get across.

The statement is to say that Microchip did not have a version of the GNU toolchain for their microcontrollers, at that time. (They do now, however.)

How do you think we can reword that to make it more clear?

**Comment by denilsonsa** [comment]
> The statement is to say that Microchip did not have a version of the GNU toolchain for their microcontrollers, at that time. (They do now, however.)

What do you mean by that? Does GCC has a version for PIC target? For instance, there is avr-gcc. That's what I understand by GNU toolchain (GNU is the G from gcc).

However, there is [SDCC](http://sdcc.sourceforge.net/), which is "Small Device C Compiler". It can compile for different targets, it is released under GPL, so it is both free software and open source. However, it is not part of the GNU project, and definitely not part of the GNU toolchain. I cannot call it a GNU compiler.

Still, even though SDCC is not part of the GNU project, it is a viable toolchain for such systems.

So, I believe the deciding factor was not if there was a GNU toolchain, but if there was an open-source toolchain. Because the most important factor is the existence of cross-platform (Win/Linux/Mac) tools licensed under an open-source/free-software license. It doesn't matter if these tools are from the GNU project or if they are from someone else (e.g. avrdude is not GNU, but is a viable solution).

Does it make sense? Also, do you have links to the currently available open-source Microchip PIC tools?

**Comment by bhagman** [comment]
Agreed. It's a bit confusing.  I'll change it to read:

> The problem with the PIC microcontrollers was that there wasn't an open source toolchain available at the time, to use a language like C to program them.
> ...
> Because of the lack of an open source toolchain, ...

Do you agree?

Even though Microchip's version of the GCC toolchain is not completely open source, it is free.

http://chipkit.net/

**Comment by denilsonsa** [comment]
Sounds better. Thanks!

**Comment by bhagman** [comment]
fixed in 3194d3200f3fafceec7048ee162128434344de14
