### ISSUE TITLE
Why Didn't Wiring Acknowledged Arduino Sooner?

### ISSUE THREAD

**Issue by bcomnes** [ArduinoHistory/arduinohistory.github.io#4]
Thank you for posting your story and history.  Its extremely interesting, especially in the light of the recent turmoil over the Arduino brand.  

I remember reading about Wiring for the first time in Making Things Talk, and always wondered what the relationship between Arduino and Wiring was, but simply could not find out a compelling description for years.

Was a version of this history and relationship officially acknowledged by the Wiring project before?  It seems like if it had, it may have curtailed some of the narrative that was promoted by the Arduino team for so long.

**Comment by bhagman** [comment]
The title of this issue is confusing.  I'm not sure exactly what you're looking for here.

**_The Untold History of Arduino**_ is a partial recount of the history of Arduino by Hernando, with supported facts.

IMO, it is Arduino's burden to acknowledge Wiring, and not the other way around.

If I'm missing what you're trying to get across, please explain it a bit further, for my sake.  Thank you!

**Comment by bcomnes** [comment]
I was trying to be clever with the title, but I think I just confused the intention of my question.  My apologies.  I agree with you that it is Arduino's burden to acknowledge Wiring. 

I wanted to ask if the the Wiring project or anyone before now had made an attempt to clarify this history to any degree at any point over the last few years when it became clear that Arduino was becoming the market leader and was doing a poor job of conveying history and attribution to Wiring. 

After thinking about the purpose of the question some more, I think that I was merely reacting my hindsight bias kicking in and really wishing that I had dug deeper into the history of the projects on my own sooner.  

Again, thank you for writing this all down!  I learned a lot, and its given me a lot to reflect on.
